### ISSUE TITLE
async/await use in Ubuntu 16.04 results in error: use of unresolved identifier 'DispatchGroup'

### ISSUE THREAD

**Issue by crarau** [freshOS/then#27]
Here is the result of `swift build`
```
/Source/Await.swift:14:17: error: use of unresolved identifier 'DispatchGroup'
    let group = DispatchGroup()
                ^~~~~~~~~~~~~
/.../.build/checkouts/then.git-5361947888815775990/Source/Async.swift:14:9: error: use of unresolved identifier 'DispatchQueue'
        DispatchQueue(label: "then.async.queue", attributes: .concurrent).async {
```

**Comment by s4cha** [comment]
This should be good in 2.2.4 : https://github.com/freshOS/then/releases/tag/2.2.4

Thanks a ton :)

**Comment by crarau** [comment]
Great! It works with the tag 2.2.4
